// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixmydtdziuhopbsnrcvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4bXlkdGR6aXVob3Bic25yY3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzgzMDksImV4cCI6MjA3MDc1NDMwOX0.AjNtjV-F-4xiAfolAmJe6Q9QK0z8AMPkR2huqthKgK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});